/// Flutter icons RebbleIconsFill
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RebbleIconsFill
///      fonts:
///       - asset: fonts/RebbleIconsFill.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RebbleIconsFill {
  RebbleIconsFill._();

  static const _kFontFam = 'RebbleIconsFill';
  static const _kFontPkg = null;

  static const IconData about_app = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customize_navigation_bar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData developer_connection_console = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devices = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locker = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications_megaphone = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rebble_store = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
