/// Flutter icons RebbleIconsStrokeOnly
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RebbleIconsStrokeOnly
///      fonts:
///       - asset: fonts/RebbleIconsStrokeOnly.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RebbleIconsStrokeOnly {
  RebbleIconsStrokeOnly._();

  static const _kFontFam = 'RebbleIconsStrokeOnly';
  static const _kFontPkg = null;

  static const IconData drag_handle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_right = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_left = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_up = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData caret_down = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_close = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_done = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_vertical = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_horizontal = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locker = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline_pin = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_to_watch_checked = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_to_watch_unchecked = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData devices = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData developer_connection_console = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about_app = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customize_nav_bar = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData system_language = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dictation_microphone = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
