/// Flutter icons PebbleWatchIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PebbleWatchIcons
///      fonts:
///       - asset: fonts/PebbleWatchIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PebbleWatchIcons {
  PebbleWatchIcons._();

  static const _kFontFam = 'PebbleWatchIcons';
  static const _kFontPkg = null;

  static const IconData classic_body_stroke = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic_body_fill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic_screen_stroke = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic_screen_fill = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic_steel_body_stroke = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic_steel_body_fill = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic_steel_screen_stroke = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic_steel_screen_fill = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_body_stroke = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_body_fill = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_screen_stroke = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_screen_fill = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_steel_body_stroke = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_steel_body_fill = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_steel_screen_stroke = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_steel_screen_fill = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_round_body_stroke = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_round_body_fill = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_round_screen_stroke = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_round_screen_fill = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pebble_2_body_stroke = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pebble_2_body_fill = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pebble_2_buttons_stroke = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pebble_2_screen_stroke = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pebble_2_screen_fill = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rebble_logo_body_stroke = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rebble_logo_body_fill = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rebble_logo_hands = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
