name: Check PR

on: [pull_request]

jobs:
  eclint:
    runs-on: ubuntu-latest
    name: "Check codestyle"
    steps:
      - uses: zbeekman/EditorConfig-Action@28b76e718c351dd35b22c8f7216192bb9de5c21b
